[package]
name = "nora_ssh_core"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.8", default-features = false }
ecdsa = "0.14"
digest = "0.10"
chacha20 = "0.9"
poly1305 = "0.7"
generic-array = "0.14"
elliptic-curve = "0.12"
subtle = "2.4"
